# Generated by Django 5.2.5 on 2025-10-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0004_initial'),
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='client',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='Включить уведомления'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторяющееся событие'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_10_minutes',
            field=models.BooleanField(default=False, verbose_name='За 10 минут'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_12_hours',
            field=models.BooleanField(default=True, verbose_name='За 12 часов'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_1_day',
            field=models.BooleanField(default=True, verbose_name='За 1 день'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_1_hour',
            field=models.BooleanField(default=True, verbose_name='За 1 час'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_1_minute',
            field=models.BooleanField(default=False, verbose_name='За 1 минуту'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_30_minutes',
            field=models.BooleanField(default=True, verbose_name='За 30 минут'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notify_3_hours',
            field=models.BooleanField(default=True, verbose_name='За 3 часа'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=100, verbose_name='Правило повторения'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='trustor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.trustor', verbose_name='Доверитель'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Встреча/Совещание'), ('deadline', 'Срок/Дедлайн'), ('reminder', 'Напоминание'), ('personal', 'Личное событие'), ('court_hearing', 'Судебное заседание'), ('client_meeting', 'Встреча с доверителем'), ('document_deadline', 'Срок подачи документов')], max_length=20, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20, verbose_name='Тип уведомления')),
                ('scheduled_time', models.DateTimeField(verbose_name='Время уведомления')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendar1.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление о событии',
                'verbose_name_plural': 'Уведомления о событиях',
                'unique_together': {('event', 'user', 'notification_type')},
            },
        ),
    ]
