# Generated by Django 5.2.5 on 2026-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0005_remove_calendarevent_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='notify_2_hours',
            field=models.BooleanField(default=True, verbose_name='За 2 часа'),
        ),
    ]
