# Generated by Django 5.2.5 on 2026-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar1', '0006_calendarevent_notify_2_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='notify_1_week',
            field=models.BooleanField(default=False, verbose_name='За 1 неделю'),
        ),
    ]
