# Generated by Django 5.2.5 on 2026-05-14 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], default='individual', max_length=20, verbose_name='Тип клиента')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО / Название организации')),
                ('contact_person', models.CharField(blank=True, help_text='Для юр. лиц — ФИО представителя', max_length=200, verbose_name='Контактное лицо')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ежемесячная сумма')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'На паузе'), ('ended', 'Завершена')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный юрист')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='retainer.subscriber', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Абонентский договор',
                'verbose_name_plural': 'Абонентские договоры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оплаты')),
                ('period', models.CharField(help_text='Напр: 2026-05 — за какой месяц', max_length=7, verbose_name='Период (YYYY-MM)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем записано')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='retainer.subscription', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата оказания')),
                ('service_type', models.CharField(choices=[('consultation', 'Консультация'), ('document', 'Подготовка документа'), ('representation', 'Представительство'), ('negotiation', 'Переговоры'), ('claim', 'Претензионная работа'), ('other', 'Иное')], default='consultation', max_length=30, verbose_name='Вид услуги')),
                ('description', models.TextField(verbose_name='Описание / результат')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Часы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='retainer.subscription', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='retainer/documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='retainer.subscription', verbose_name='Договор')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='retainer.subscriptionservice', verbose_name='Услуга (необязательно)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
