# Generated by Django 5.2.5 on 2025-12-11 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_status_alter_caseparticipant_role'),
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_number', models.CharField(blank=True, max_length=100, verbose_name='Номер соглашения')),
                ('agreement_date', models.DateField(blank=True, null=True, verbose_name='Дата соглашения')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма договора')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено по договору')),
                ('company_share_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент компании')),
                ('lawyers_share_percent', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Процент юристов/адвокатов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='cases.case', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Финансы дела',
                'verbose_name_plural': 'Финансы дел',
            },
        ),
        migrations.CreateModel(
            name='CaseFinanceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_of_pool', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доля от 70% (в %)')),
                ('amount_full', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма при полной оплате договора')),
                ('amount_current', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма к выплате с учётом текущей оплаты')),
                ('is_manual', models.BooleanField(default=False, help_text='Если включено — доля выставлена вручную бухгалтером/директором.', verbose_name='Ручная корректировка')),
                ('case_finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='finance.casefinance', verbose_name='Финансы дела')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник (юрист/адвокат)')),
            ],
            options={
                'verbose_name': 'Доля сотрудника в 70%',
                'verbose_name_plural': 'Доли сотрудников в 70%',
                'unique_together': {('case_finance', 'employee')},
            },
        ),
    ]
