# Generated by Django 5.2.5 on 2025-12-15 05:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_casefinance_casefinanceshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefinance',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма договора (100%)'),
        ),
        migrations.AlterField(
            model_name='casefinanceshare',
            name='amount_current',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма с учётом текущей оплаты'),
        ),
    ]
