# Generated by Django 5.2.5 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_casefinance_contract_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='agreement_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер соглашения'),
        ),
    ]
