# Generated by Django 5.2.5 on 2026-02-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financialtransaction_agreement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefinance',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок погашения по соглашению'),
        ),
    ]
