# Generated by Django 5.2.5 on 2025-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustor',
            name='passport_number',
            field=models.CharField(max_length=7, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='passport_series',
            field=models.CharField(max_length=14, verbose_name='Серия паспорта'),
        ),
    ]
