# Generated by Django 5.2.5 on 2025-10-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_trustor_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustor',
            name='inn',
            field=models.CharField(blank=True, max_length=14, verbose_name='ИНН'),
        ),
    ]
