# Generated by Django 5.2.5 on 2025-10-28 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_trustor_inn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustor',
            name='primary_contact',
        ),
        migrations.AddField(
            model_name='trustor',
            name='primary_contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='trustors', to=settings.AUTH_USER_MODEL, verbose_name='Ответственные (юрист/адвокат)'),
        ),
    ]
