# Generated by Django 5.2.5 on 2026-02-12 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_trustor_primary_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='inn',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='passport_issued_by',
            field=models.TextField(blank=True, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='passport_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='passport_series',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+99655090400'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='registration_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='residence_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
