# Generated by Django 5.2.5 on 2026-02-24 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_trustor_created_at_alter_trustor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustorRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(blank=True, default='', max_length=255, verbose_name='Основание (доверенность/ордер)')),
                ('doc_number', models.CharField(blank=True, default='', max_length=100, verbose_name='№ документа')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Срок действия до')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_representative_links', to='clients.trustor', verbose_name='Представитель')),
                ('trustor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_links', to='clients.trustor', verbose_name='Доверитель')),
            ],
            options={
                'verbose_name': 'Связь доверитель-представитель',
                'verbose_name_plural': 'Связи доверитель-представитель',
                'unique_together': {('trustor', 'representative')},
            },
        ),
        migrations.AddField(
            model_name='trustor',
            name='representatives',
            field=models.ManyToManyField(blank=True, related_name='represented_trustors', through='clients.TrustorRepresentation', to='clients.trustor', verbose_name='Представители'),
        ),
    ]
