# Generated by Django 5.2.5 on 2026-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_trustorrepresentation_trustor_representatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustor',
            name='location_details',
            field=models.CharField(blank=True, default='', help_text='Напр.: СИЗО-1, г. Бишкек, камера 12 / адрес учреждения', max_length=255, verbose_name='Детали местонахождения'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='location_status',
            field=models.CharField(choices=[('free', 'На свободе'), ('ukzh', 'УКЖ'), ('ivs', 'ИВС'), ('ik', 'ИК'), ('sizo', 'СИЗО')], default='free', max_length=20, verbose_name='Местонахождение'),
        ),
    ]
