# Generated by Django 5.2.5 on 2026-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_trustor_location_details_trustor_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustor',
            name='preventive_measure',
            field=models.CharField(choices=[('none', 'Нет'), ('detention', 'Заключение под стражу'), ('house_arrest', 'Домашний арест'), ('arrest', 'Арест'), ('other', 'Другое')], default='none', max_length=20, verbose_name='Мера пресечения'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='preventive_measure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата избрания меры'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='preventive_measure_details',
            field=models.CharField(blank=True, default='', help_text='Напр.: постановление суда, срок до, условия и т.д.', max_length=255, verbose_name='Детали меры пресечения'),
        ),
    ]
