# Generated by Django 5.2.5 on 2026-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_trustor_preventive_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustor',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], default='individual', max_length=10, verbose_name='Тип лица'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('ОсОО', 'ОсОО'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО'), ('АО', 'АО'), ('ГП', 'ГП (Государственное предприятие)'), ('МП', 'МП (Муниципальное предприятие)'), ('ИП', 'ИП (Индивидуальный предприниматель)'), ('НКО', 'НКО'), ('Филиал', 'Филиал'), ('Представительство', 'Представительство'), ('Другое', 'Другое')], max_length=20, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AddField(
            model_name='trustor',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='trustor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
