# Generated by Django 5.2.5 on 2025-10-19 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Аккаунт активен')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('notify_1_day', models.BooleanField(default=True, verbose_name='За 1 день')),
                ('notify_12_hours', models.BooleanField(default=True, verbose_name='За 12 часов')),
                ('notify_3_hours', models.BooleanField(default=True, verbose_name='За 3 часа')),
                ('notify_1_hour', models.BooleanField(default=True, verbose_name='За 1 час')),
                ('notify_30_minutes', models.BooleanField(default=True, verbose_name='За 30 минут')),
                ('notify_10_minutes', models.BooleanField(default=True, verbose_name='За 10 минут')),
                ('notify_1_minute', models.BooleanField(default=True, verbose_name='За 1 минуту')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата привязки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram аккаунт',
                'verbose_name_plural': 'Telegram аккаунты',
            },
        ),
    ]
