# Generated by Django 5.2.5 on 2026-02-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Управляющий партнёр'), ('deputy_director', 'Зам.директора'), ('manager', 'Менеджер'), ('lawyer', 'Юрист'), ('advocate', 'Адвокат'), ('accountant', 'Бухгалтер'), ('hr', 'HR-менеджер'), ('admin', 'Админ'), ('trainee', 'Стажер'), ('external_lawyer', 'Внешний юрист')], default='lawyer', max_length=20),
        ),
    ]
