# Generated by Django 5.2.5 on 2026-04-26 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineeprofile',
            name='curator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['lawyer', 'advocate', 'managing_partner_advocate']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'Управляющий партнёр'), ('managing_partner_advocate', 'Управляющий партнёр-Адвокат'), ('deputy_director', 'Зам.директора'), ('manager', 'Менеджер'), ('lawyer', 'Юрист'), ('advocate', 'Адвокат'), ('accountant', 'Бухгалтер'), ('hr', 'HR-менеджер'), ('admin', 'Админ'), ('trainee', 'Стажер'), ('external_lawyer', 'Внешний юрист')], default='lawyer', max_length=30),
        ),
    ]
