# Generated by Django 5.2.5 on 2026-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_traineeprofile_curator_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='notify_2_hours',
            field=models.BooleanField(default=True, verbose_name='За 2 часа'),
        ),
    ]
