# Generated by Django 5.2.5 on 2026-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_telegramaccount_notify_2_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='notify_1_week',
            field=models.BooleanField(default=True, verbose_name='За 1 неделю'),
        ),
    ]
