# Generated by Django 5.2.5 on 2026-10-09 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Часть публичной ссылки. Если оставить пустым — сформируется из названия.', max_length=200, unique=True, verbose_name='Адрес (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание / приветственный текст')),
                ('thank_you_text', models.TextField(blank=True, default='Спасибо! Ваш ответ сохранён.', verbose_name='Текст после отправки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован (доступен по ссылке)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст вопроса')),
                ('field_type', models.CharField(choices=[('short_text', 'Короткий текст (одна строка)'), ('long_text', 'Длинный текст (абзац)'), ('email', 'Email'), ('phone', 'Телефон'), ('date', 'Дата'), ('rating', 'Шкала-оценка (1–5)'), ('choice', 'Один вариант из списка'), ('checkbox', 'Несколько вариантов из списка')], default='short_text', max_length=20, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='Пояснение под вопросом')),
                ('options', models.TextField(blank=True, help_text='Только для «Один вариант» / «Несколько вариантов» — каждый вариант с новой строки.', verbose_name='Варианты ответа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['survey', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Ответ на опросник',
                'verbose_name_plural': 'Ответы на опросники',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, help_text='Текст, выбранное значение шкалы/варианта, или варианты через запятую для чекбоксов.', verbose_name='Значение')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion', verbose_name='Вопрос')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='Прохождение')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
                'ordering': ['question__order', 'id'],
                'unique_together': {('response', 'question')},
            },
        ),
    ]
