# Generated by Django 5.2.5 on 2026-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Отдел / Направление')),
                ('employment', models.CharField(choices=[('full', 'Полная занятость'), ('part', 'Частичная занятость'), ('intern', 'Стажировка'), ('remote', 'Удалённо'), ('contract', 'Договор / Проект')], default='full', max_length=20, verbose_name='Тип занятости')),
                ('salary', models.CharField(blank=True, help_text='Напр: от 30 000 сом или по договорённости', max_length=100, verbose_name='Зарплата')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
