# Generated by Django 5.2.5 on 2026-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_add_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название дела')),
                ('practice_area', models.CharField(choices=[('civil', 'Гражданское право'), ('criminal', 'Уголовное право'), ('family', 'Семейное право'), ('labor', 'Трудовое право'), ('administrative', 'Административное'), ('tax', 'Налоговое право'), ('corporate', 'Корпоративное'), ('other', 'Другое')], default='civil', max_length=30, verbose_name='Отрасль')),
                ('description', models.TextField(verbose_name='Описание дела')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к исполнителю')),
                ('price', models.CharField(blank=True, help_text='Напр: 15 000 сом, или оставьте пустым для «Договорная»', max_length=120, verbose_name='Цена')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='Цена договорная')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи заявок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Аутсорс дело',
                'verbose_name_plural': 'Аутсорс дела',
                'ordering': ['-created_at'],
            },
        ),
    ]
