# Generated by Django 5.2.5 on 2026-04-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_outsourcecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Content (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='content_ky',
            field=models.TextField(blank=True, verbose_name='Текст (KY)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Excerpt (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='excerpt_ky',
            field=models.TextField(blank=True, verbose_name='Коротко (KY)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (KY)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='Content (EN)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='content_ky',
            field=models.TextField(blank=True, verbose_name='Описание (KY)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='excerpt_en',
            field=models.TextField(blank=True, verbose_name='Excerpt (EN)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='excerpt_ky',
            field=models.TextField(blank=True, verbose_name='Коротко (KY)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AddField(
            model_name='publiccase',
            name='title_ky',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (KY)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст (RU)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Коротко (RU)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Коротко (RU)'),
        ),
        migrations.AlterField(
            model_name='publiccase',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название кейса (RU)'),
        ),
    ]
