# Generated by Django 5.2.5 on 2026-09-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_add_multilang_fields_news_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-is_partner', 'order', 'id'], 'verbose_name': 'Публичная карточка команды (сайт)', 'verbose_name_plural': 'Команда на сайте (страница «О нас»)'},
        ),
    ]
