# Generated by Django 5.2.5 on 2025-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Статья ук - описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('paused', 'На паузе'), ('completed', 'Завершено'), ('archived', 'Архив')], default='open', max_length=20, verbose_name='Статус дела')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Дела',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('civil_economic', 'Гражданские - Экономические дела'), ('administrative', 'Административные дела'), ('civil_administrative', 'Гражданский – Административный'), ('criminal', 'Уголовные дела'), ('offenses', 'Правонарушения')], max_length=50, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория дела',
                'verbose_name_plural': 'Категории дел',
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, verbose_name='Текстовое значение')),
                ('file_value', models.FileField(blank=True, upload_to='case_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ дела',
                'verbose_name_plural': 'Документы дел',
            },
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_participant', models.BooleanField(default=False, help_text='Является ли этот доверитель основным по делу', verbose_name='Основной доверитель')),
                ('representation_basis', models.TextField(blank=True, verbose_name='Основание представительства')),
                ('powers_details', models.TextField(blank=True, verbose_name='Сведения о полномочиях')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Участник дела',
                'verbose_name_plural': 'Участники дела',
            },
        ),
        migrations.CreateModel(
            name='CaseParticipantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=50, verbose_name='Код роли')),
                ('role_name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Роль участника дела',
                'verbose_name_plural': 'Роли участников дела',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Этап дела',
                'verbose_name_plural': 'Этапы дел',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('date', 'Дата'), ('select', 'Выбор из списка'), ('number', 'Число')], max_length=10, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('options', models.TextField(blank=True, help_text="Для полей типа 'select' укажите варианты через запятую", verbose_name='Варианты выбора')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Поле этапа',
                'verbose_name_plural': 'Поля этапов',
                'ordering': ['stage', 'order'],
            },
        ),
    ]
