# Generated by Django 5.2.5 on 2025-09-29 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cases', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный юрист/адвокат'),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory', verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='cases.case', verbose_name='Дело'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='trustor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participants', to='clients.trustor', verbose_name='Доверитель'),
        ),
        migrations.AddField(
            model_name='caseparticipantrole',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_roles', to='cases.casecategory', verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.caseparticipantrole', verbose_name='Роль в деле'),
        ),
        migrations.AddField(
            model_name='casestage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cases.casecategory', verbose_name='Категория дела'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.casestage', verbose_name='Этап'),
        ),
        migrations.AddField(
            model_name='case',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.casestage', verbose_name='Текущий этап'),
        ),
        migrations.AddField(
            model_name='stagefield',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cases.casestage', verbose_name='Этап дела'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.stagefield', verbose_name='Поле'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipantrole',
            unique_together={('category', 'role_code')},
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'trustor', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='casestage',
            unique_together={('category', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='casedocument',
            unique_together={('case', 'stage', 'field')},
        ),
    ]
