# Generated by Django 5.2.5 on 2025-09-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='client',
        ),
    ]
