# Generated by Django 5.2.5 on 2025-09-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер дела в суде'),
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Наименование суда'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО судьи'),
        ),
    ]
