# Generated by Django 5.2.5 on 2025-10-29 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_case_number_case_court_name_case_judge_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='responsible_lawyer',
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('paused', 'Приостановлено'), ('completed', 'Завершено'), ('archived', 'Архив')], default='open', max_length=20, verbose_name='Статус дела'),
        ),
        migrations.AddField(
            model_name='case',
            name='responsible_lawyer',
            field=models.ManyToManyField(blank=True, null=True, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный юрист/адвокат'),
        ),
    ]
