# Generated by Django 5.2.5 on 2025-11-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_remove_case_responsible_lawyer_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В процессе'), ('paused', 'Приостановлено'), ('completed', 'Завершено'), ('archived', 'Архив')], default='open', max_length=20, verbose_name='Статус дела'),
        ),
        migrations.AlterField(
            model_name='caseparticipant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.caseparticipantrole', verbose_name='Статус в деле'),
        ),
    ]
