# Generated by Django 5.2.5 on 2025-12-15 05:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_alter_case_status_alter_caseparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма договора (100%)'),
        ),
    ]
