# Generated by Django 5.2.5 on 2026-02-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_contract_amount'),
        ('clients', '0007_trustorrepresentation_trustor_representatives'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='participant_type',
            field=models.CharField(choices=[('trustor', 'Доверитель'), ('representative', 'Представитель')], default='trustor', max_length=20, verbose_name='Тип участия'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='represents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represented_in_cases', to='clients.trustor', verbose_name='Кого представляет'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'trustor', 'role', 'participant_type', 'represents')},
        ),
    ]
