# Generated by Django 5.2.5 on 2026-03-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_caseparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='internal_number',
            field=models.CharField(blank=True, help_text='Напр.: KP-001, 2026-15, A/12', max_length=50, null=True, verbose_name='Номер дела (внутренний)'),
        ),
        migrations.AddField(
            model_name='case',
            name='internal_year',
            field=models.PositiveIntegerField(default=2026, help_text='Для уникальности нумерации по году', verbose_name='Год номера'),
        ),
    ]
