# Generated by Django 5.2.5 on 2026-05-22 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_internal_number_case_internal_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='name',
            field=models.CharField(choices=[('civil_economic', 'Гражданские - Экономические дела'), ('administrative', 'Административные дела'), ('civil_administrative', 'ГД'), ('criminal', 'Уголовные дела'), ('offenses', 'Правонарушения')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='CaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название папки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_folders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casefolder', verbose_name='Папка'),
        ),
    ]
