# Generated by Django 5.2.5 on 2026-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_internal_number_case_internal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='name',
            field=models.CharField(choices=[('civil_economic', 'Гражданские - Экономические дела'), ('administrative', 'Административные дела'), ('civil_administrative', 'ГД'), ('criminal', 'Уголовные дела'), ('offenses', 'Правонарушения')], max_length=50, unique=True, verbose_name='Название категории'),
        ),
    ]
