# Generated by Django 5.2.5 on 2026-09-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_case_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='agreement_file',
            field=models.FileField(blank=True, help_text='Формируется автоматически, когда заполнены категория, сумма договора, ответственный юрист и основной доверитель по делу.', null=True, upload_to='case_agreements/', verbose_name='Файл соглашения'),
        ),
        migrations.AddField(
            model_name='case',
            name='agreement_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования соглашения'),
        ),
    ]
