# Generated by Django 5.2.5 on 2026-05-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_add_case_folder'),
        ('cases', '0011_alter_casecategory_name'),
    ]

    operations = [
    ]
