# Generated by Django 5.2.5 on 2026-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_merge_20260918_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagefield',
            name='is_agreement_document',
            field=models.BooleanField(default=False, help_text='Загруженный сюда файл будет считаться подписанным соглашением по делу — на него будет вести отдельная кнопка «Соглашение» в списке дел.', verbose_name='Это поле — соглашение'),
        ),
    ]
