# Generated by Django 5.2.5 on 2026-09-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_case_agreement_file_case_agreement_generated_at'),
        ('cases', '0012_merge_20260523_1007'),
    ]

    operations = [
    ]
