# Generated by Django 5.2.5 on 2026-10-08 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_stagefield_is_agreement_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='manual_progress',
            field=models.BooleanField(default=False, help_text='Если отмечено, процент не пересчитывается автоматически при загрузке документов — значение задаёт сам пользователь.', verbose_name='Процент заполненности указан вручную'),
        ),
        migrations.AlterField(
            model_name='case',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)'),
        ),
    ]
