# Generated by Django 5.2.5 on 2025-09-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='Всего дел')),
                ('completed_cases', models.PositiveIntegerField(default=0, verbose_name='Завершенные дела')),
                ('average_progress', models.FloatField(default=0, verbose_name='Средний прогресс')),
                ('success_rate', models.FloatField(default=0, verbose_name='Процент успешных дел')),
                ('client_satisfaction', models.FloatField(default=0, verbose_name='Удовлетворенность клиентов')),
                ('efficiency_score', models.FloatField(default=0, verbose_name='Оценка эффективности')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сгенерированный доход')),
                ('total_score', models.FloatField(default=0, verbose_name='Общий балл')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Рейтинг юриста',
                'verbose_name_plural': 'Рейтинги юристов',
                'ordering': ['period_start', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='CaseComplexity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity_level', models.PositiveSmallIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Уровень сложности')),
                ('complexity_factors', models.TextField(verbose_name='Факторы сложности')),
                ('estimated_hours', models.PositiveIntegerField(default=0, verbose_name='Оценочное время (часы)')),
                ('actual_hours', models.PositiveIntegerField(default=0, verbose_name='Фактическое время (часы)')),
                ('rated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case', verbose_name='Дело')),
            ],
            options={
                'verbose_name': 'Сложность дела',
                'verbose_name_plural': 'Сложности дел',
            },
        ),
    ]
