# Generated by Django 5.2.5 on 2026-04-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('court', 'Судебная система'), ('prosecutor', 'Прокуратура'), ('investigative', 'Следственная служба'), ('police', 'МВД / Полиция'), ('notary', 'Нотариат'), ('bailiff', 'Служба судебных исполнителей'), ('justice', 'Министерство юстиции'), ('other', 'Другое')], max_length=30, verbose_name='Тип организации')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('district', models.CharField(blank=True, max_length=200, verbose_name='Район / город')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Телефон(ы)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('head_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя')),
                ('head_position', models.CharField(blank=True, max_length=200, verbose_name='Должность руководителя')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir_created', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='directory.region', verbose_name='Область / регион')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['org_type', 'region__name', 'name'],
            },
        ),
    ]
