# Generated by Django 5.2.5 on 2026-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='Время')),
                ('client_name', models.CharField(blank=True, max_length=300, verbose_name='ФИО клиента / партнёра')),
                ('opposing_party', models.CharField(blank=True, max_length=300, verbose_name='ФИО второй стороны')),
                ('court', models.CharField(blank=True, max_length=300, verbose_name='Судебная инстанция / орган')),
                ('responsible_staff', models.CharField(blank=True, max_length=200, verbose_name='Ответственный сотрудник')),
                ('case_description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание дела')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись графика',
                'verbose_name_plural': 'График дел',
                'ordering': ['date', 'time'],
            },
        ),
    ]
