# Generated by Django 5.2.5 on 2026-04-24 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='notify_users',
            field=models.ManyToManyField(blank=True, related_name='schedule_entries', to=settings.AUTH_USER_MODEL, verbose_name='Уведомить в Telegram'),
        ),
        migrations.CreateModel(
            name='ScheduleNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.IntegerField(verbose_name='За сколько минут')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='schedule.scheduleentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'unique_together': {('entry', 'user', 'minutes_before')},
            },
        ),
    ]
