# Generated by Django 5.2.5 on 2026-04-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, choices=[('lawyer', 'Адвокат'), ('advocate', 'Юрист'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('hr', 'HR-специалист'), ('other', 'Другое')], max_length=50, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='hr/passports/', verbose_name='Копия паспорта')),
                ('resume', models.FileField(blank=True, null=True, upload_to='hr/resumes/', verbose_name='Резюме')),
                ('personal_file', models.FileField(blank=True, null=True, upload_to='hr/personal_files/', verbose_name='Личное дело')),
                ('work_book', models.FileField(blank=True, null=True, upload_to='hr/work_books/', verbose_name='Трудовая книжка')),
                ('no_criminal_record', models.FileField(blank=True, null=True, upload_to='hr/criminal_records/', verbose_name='Справка о несудимости')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='hr/diplomas/', verbose_name='Диплом')),
                ('autobiography', models.FileField(blank=True, null=True, upload_to='hr/autobiographies/', verbose_name='Автобиография')),
                ('job_application', models.FileField(blank=True, null=True, upload_to='hr/job_applications/', verbose_name='Заявление на работу')),
                ('employment_contract', models.FileField(blank=True, null=True, upload_to='hr/contracts/', verbose_name='Трудовой договор')),
                ('mj_notification', models.FileField(blank=True, null=True, upload_to='hr/mj_notifications/', verbose_name='Уведомление МЮ КР')),
                ('bar_notification', models.FileField(blank=True, null=True, upload_to='hr/bar_notifications/', verbose_name='Уведомление Адвокатуры КР')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_created', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Сотрудник (кадры)',
                'verbose_name_plural': 'Сотрудники (кадры)',
                'ordering': ['full_name'],
            },
        ),
    ]
